Repository ant-design/sunflower, pull requests merged in 2019-11, with the labels that each got.

#70 fix: formdefaultFormValues unmounted update state warning
  packages/sunflower-antd-form/src/index.tsx
Labels: bug

#72 fix: TS issues
  packages/sunflower-antd-form-table/src/index.tsx
Labels: bug

#73 feat: 支持返回上一步时可配置是否校验表单 & 对外暴露表单校验的结果
  docs/hooks/sunflower-antd-steps-form.mdx
  packages/sunflower-antd-steps-form/src/index.tsx
Labels: enhancement

#74 fix: eslint
  .eslintrc.js
  packages/sunflower-antd-form/src/index.tsx
Labels: CI
